import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { build } from 'esbuild';

/**
 * Builds the lazily-loaded storefront bundles.
 *
 * Theme app extension assets are served verbatim, so this is the only place a
 * build step can happen — and each bundle exists for the same single reason:
 * it imports code from `@codflow/shared` that the API also runs.
 *
 *   src/form.ts    -> the real validation engine, the same functions the API
 *                     runs when it decides whether to create an order.
 *   src/pixels.ts  -> the deduplication id and the provider event-name table,
 *                     the same ones the server-side dispatcher uses.
 *
 * The alternative in both cases is hand-writing a second copy in vanilla JS.
 * That eventually disagrees with the server, and the symptom is either a
 * shopper who passes every check in front of them and is then rejected with no
 * way to see why, or a merchant whose conversions are quietly counted twice.
 *
 * Output is committed rather than gitignored: `shopify app deploy` uploads
 * whatever is in `assets/`, so the files have to exist before deploy regardless
 * of whether CI ran this first.
 */

const here = dirname(fileURLToPath(import.meta.url));
const isWatch = process.argv.includes('--watch');

const options = {
  entryPoints: [resolve(here, 'src/form.ts'), resolve(here, 'src/pixels.ts')],
  // One entry point per output file, named after its source. `outfile` only
  // accepts a single entry, so the directory form is what allows two.
  outdir: resolve(here, '../extensions/codflow-theme/assets'),
  entryNames: 'codflow-[name]',
  bundle: true,
  format: 'iife',
  // Matches the floor of Shopify's supported storefront browsers. Going newer
  // would ship optional chaining to browsers that cannot parse it, and a syntax
  // error takes the whole bundle down rather than degrading one feature.
  target: ['es2019'],
  platform: 'browser',
  minify: true,
  // Shipped so a merchant's developer can debug the form in their own store
  // without reverse-engineering minified output.
  sourcemap: true,
  legalComments: 'none',
  banner: {
    js: '/* CodFlow — generated by extensions/codflow-theme/build.mjs. Do not edit. */',
  },
  logLevel: 'info',
};

if (isWatch) {
  const context = await (await import('esbuild')).context(options);
  await context.watch();
  console.log('Watching theme-src/src…');
} else {
  const result = await build(options);

  if (result.errors.length > 0) {
    process.exit(1);
  }
}
